/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#006c49',
        'background': '#101415',
        'surface-tint': '#4edea3',
        'tertiary': '#bcc7de',
        'on-tertiary-fixed-variant': '#3c475a',
        'tertiary-fixed': '#d8e3fb',
        'on-primary-container': '#00422b',
        'secondary': '#bec6e0',
        'secondary-container': '#3f465c',
        'surface-container': '#1d2022',
        'tertiary-container': '#98a3ba',
        'on-background': '#e0e3e5',
        'error-container': '#93000a',
        'surface-bright': '#363a3b',
        'secondary-fixed-dim': '#bec6e0',
        'primary-container': '#10b981',
        'on-secondary-container': '#adb4ce',
        'surface-container-highest': '#323537',
        'on-primary-fixed': '#002113',
        'surface-variant': '#323537',
        'surface': '#101415',
        'on-secondary': '#283044',
        'on-tertiary': '#263143',
        'on-error-container': '#ffdad6',
        'error': '#ffb4ab',
        'primary-fixed': '#6ffbbe',
        'surface-dim': '#101415',
        'on-secondary-fixed': '#131b2e',
        'tertiary-fixed-dim': '#bcc7de',
        'outline-variant': '#3c4a42',
        'surface-container-low': '#191c1e',
        'primary-fixed-dim': '#4edea3',
        'on-surface-variant': '#bbcabf',
        'surface-container-high': '#272a2c',
        'inverse-surface': '#e0e3e5',
        'on-primary-fixed-variant': '#005236',
        'secondary-fixed': '#dae2fd',
        'on-secondary-fixed-variant': '#3f465c',
        'primary': '#4edea3',
        'on-primary': '#003824',
        'on-tertiary-container': '#2e394c',
        'on-error': '#690005',
        'surface-container-lowest': '#0b0f10',
        'on-tertiary-fixed': '#111c2d',
        'on-surface': '#e0e3e5',
        'inverse-on-surface': '#2d3133',
        'outline': '#86948a',
      },
      spacing: {
        'container-max': '1280px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'gutter': '24px',
        'unit': '4px',
        'section-padding': '80px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'display-lg': ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'label-sm': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'headline-lg-mobile': ['Manrope', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
        'manrope': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
