services:
  - type: web
    name: miles-backend
    runtime: node
    rootDir: .
    buildCommand: npm --prefix Backend install && npm --prefix Frontend/MILES install && npm --prefix Frontend/MILES run build
    startCommand: npm --prefix Backend start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OFFICIAL_MILES_EMAIL
        sync: false
      - key: MILES_REGISTRATION_SECRET
        sync: false
      - key: ADMIN_REGISTRATION_SECRET
        sync: false
